server:
  port: 8080

logging:
  #file: log/log.log
  level:
     root: info
     com.codeya.springboot: debug
  pattern:
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}:%L){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
    file: -%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}:%L:%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

test:
    properties1: hellooooooooooooo   #相当于 在properties文件里的test.properties1=hellooooooooooooo
    properties2: 11
spring:
  profiles:
    active: #dev  #部署到现场的时候可以启用。。也可以启动时指定此参数
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
        #url: jdbc:oracle:thin:@10.45.59.178:1521:res178
        #username: resltossGeneral
        #password: resltossGeneral
    url: jdbc:oracle:thin:@10.45.59.190:1521:orcl
    username: RES_CUGR_TEST
    password: RES_CUGR_TEST
  resources:
  application:
    name: qll-service
   # static-locations:
mybatis:
  mapper-locations: classpath*:com/codeya/springboot/**/dao/*.xml
#外系统登录
outer:
  login:
    ask_resouces: #是个map
      RES_GIS: resGis
      Other: other
    description: hahahaha

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.98.63.5:8761/eureka/